#server:
#  port: 8215
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  elasticsearch:
#    rest:
#      uris: http://localhost:9200
#  application:
#    name: server-search
##    stream-kakfa
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: shopping
#          content-type: application/json
#          group: myGroup
#        output:
#          destination: shopping
#          content-type: application/json
#      kafka:
#        binder:
#          brokers: localhost:9092
##
#
#feign:
#  sentinel:
#    enabled: true
#  client:
#    config:
#      default:
#        connect-timeout: 30000
#        read-timeout: 50000
#  application:
#    name: service-search