#server:
#  port: 8215
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#spring:
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    timeout: 1800000
#    password:
#    lettuce:
#      pool:
#        max-active: 20 #最大连接数
#        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
#        max-idle: 5    #最大空闲
#        min-idle: 0     #最小空闲
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    #    开启生产者的确认机制 异步回调 定义一个confirmCallBack MQ返回结果时会回调这个callBack
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    template:
#      mandatory: true
#elastic.hostname: 127.0.0.1
#elastic.port: 9200